レビュー箇所の修正
koya-sato-017/koyasato pull request #2
Opened 2020-07-06 07:55 UTC by koya-sato-017

fix: 51,65,259 タグ名の修正
add: 106-162 ul,liタグの追加
add: alt属性の追加

2020-07-07 08:51 UTC, n06Ar requested changes
24行目のメニューの` <div class="globalNavi">`ですが、divタグからnavタグに置き換えをお願いします
[nav](https://developer.mozilla.org/ja/docs/Web/HTML/Element/nav)タグは、サイトのメニューなどのリンクをまとめたところに示すためのタグになります

2020-07-07 08:51 UTC, n06Ar commented on README.md
>    <div class="articleText">
ここの49行目か63行目（模写するなら）から171行目を`main`タグと`aricle`で囲ってください
[main](https://developer.mozilla.org/ja/docs/Web/HTML/Element/main)タグは、ウェブページのメインコンテンツを示し、[article](https://developer.mozilla.org/ja/docs/Web/HTML/Element/main)タグは、ウェブページの記事に当たるコンテンツを示すためです

ex)
```html
<main>
    <article>
        <div  class="articleText">
        ...
    </article>
</main>
```

2020-07-08 09:01 UTC, n06Ar approved these changes
LGTM OKです！この後提出するCSSに合わせてHTMLにdivタグやクラスを追加してみてください

2020-07-23 07:51 UTC, n06Ar requested changes
画面のレイアウトを合わせてレビューしました
コードは該当の箇所を、デザイン関連で気になるところは下記になります

- bodyタグにmarginが発生している（normalize.cssを読み込んでいないことが原因です）
- パンくずメニューも同時に画面に追従している
- リンクの色（リンクを踏んだ後の色も含めて）が元のページと異なります
- `.footerMain`のデザインが元のページと異なります
-  `copyright`の位置が元のページと異なります

レビューの箇所が修正された後に細かいレイアウト周りのレビューをしていきます

2020-07-23 07:51 UTC, n06Ar commented on common/css/style.css
> +#btn01.active span:nth-of-type(1) {
`#btn01`などの数字を使った（マジックナンバー）を使用しないようにしてください
他者が見た時に何のボタンかわからないことと、`#btn02`がないのに数字を振っていることにより他にも類似のボタンがあると想像し混乱するためです

2020-07-23 07:51 UTC, n06Ar commented on index.html
> +<link rel="stylesheet" href="common/css/normalize.css">
`normalize.css`（リセットCSS）がファイルとして見当たりません
未コミットやプッシュ漏れ等の確認をお願いします

2020-07-23 07:51 UTC, n06Ar commented on index.html
> +        <li><img src="https://www.nri.com/-/media/Corporate/jp/Images/common/header/glass.svg" alt="検索"></li>
HTMLの時に指摘せず申し訳ないですが、画像などはこのリポジトリ内に保存して参照するようにしてください
現状ですと`https://www.nri.com/`のサーバにある画像を参照して表示しているので避けてください
類似箇所も同様です

2020-07-23 07:51 UTC, n06Ar commented on index.html
> +                <a class="linkLeft" href="https://www.nri.com/jp/company/whats/story03">&lt; ビジネスモデルの特徴</a>
HTMLの時に指摘せず申し訳ないですが、`href`は`href="#"`と入れるようにしてください
類似箇所も同様です

2020-07-23 07:51 UTC, n06Ar commented on index.html
> +<footer>
`footer`タグ中のインデントサイズが4ではなくなっています

2020-07-23 07:51 UTC, n06Ar commented on index.html
> +<meta name="description" content="">
HTMLの時に指摘せず申し訳ないですが、`meta`タグの`description`と`keyword`とOGP系を内容付きで追記しておいてください
SEOやSNSで共有した際に使われる設定のため設定をしてください

2020-07-23 07:51 UTC, n06Ar commented on index.html
> +      <svg width="58px" height="29px" viewBox="0 0 68 35" version="1.1" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink" style="cursor: pointer;">
HTMLの時に指摘せず申し訳ないですが、画像などはこのリポジトリ内に保存して参照するようにしてください

2020-07-23 07:51 UTC, n06Ar commented on common/css/style.css
> +    position: fixed;
今回のページのデザインでは、`position:fixed`と`top`、`left`、`right`を組み合わせて使う必要があります

2020-07-23 07:51 UTC, n06Ar commented on index.html
> +<main>
headerタグのレイアウトを修正したあとで良いのですが、headerタグとmainタグ間のmarginを修正してください
現状ですと余白が不足しています

2020-07-23 07:53 UTC, n06Ar commented on common/css/style.css
> +    color: #fff;
これはin my opinionです
文字コードが、3文字と6文字が散見されているので、6文字に統一しても良いかと思いました

2020-07-24 23:38 UTC, koya-sato-017 commented on common/css/style.css
> +#btn01.active span:nth-of-type(1) {
コピペしたものを使用していました。
削除しました。

2020-07-24 23:38 UTC, koya-sato-017 commented on index.html
> +<link rel="stylesheet" href="common/css/normalize.css">
コミット、プッシュしました。

2020-07-24 23:39 UTC, koya-sato-017 commented on index.html
> +        <li><img src="https://www.nri.com/-/media/Corporate/jp/Images/common/header/glass.svg" alt="検索"></li>
該当箇所は、画像ファイルをリポジトリ内に保存しました。

2020-07-24 23:53 UTC, koya-sato-017 commented on index.html
> +                <a class="linkLeft" href="https://www.nri.com/jp/company/whats/story03">&lt; ビジネスモデルの特徴</a>
該当箇所を修正しました。

2020-07-25 00:57 UTC, koya-sato-017 commented on index.html
> +<meta name="description" content="">
記述しました。

2020-07-25 01:47 UTC, koya-sato-017 commented on index.html
> +      <svg width="58px" height="29px" viewBox="0 0 68 35" version="1.1" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink" style="cursor: pointer;">
画像ファイルをリポジトリ内に保存しました。

2020-07-25 01:48 UTC, koya-sato-017 commented on common/css/style.css
> +    position: fixed;
cssを修正しました。

2020-07-25 02:35 UTC, koya-sato-017 commented on common/css/style.css
> +    color: #fff;
6文字に統一しました。

2020-07-26 14:03 UTC, n06Ar requested changes
追加でレビューをしました
ご確認をお願いします

また、下記ファイルを追加されていますがこちらは使われていないように見受けられます
もし不要であれば削除してください
- images/SVG namespace.htm
- images/SVG namespace/w3c_home
- images/XLink namespace.htm
- images/XLink namespace/base.css

2020-07-26 14:03 UTC, n06Ar commented on common/css/style.css
> +    font-size: 1px;
1pxは見えないので大きさを修正してください

2020-07-26 14:03 UTC, n06Ar commented on common/css/style.css
> +    background: url(../../images/PDF_24.png) no-repeat;
ここの画像が見つからないので確認をお願いします

2020-07-26 14:03 UTC, n06Ar commented on common/css/style.css
> +    align-items: center;
z-indexをつけてください
z-indexがないので下にスクロールすると一部コンテンツの方が上に表示されます

2020-07-26 14:03 UTC, n06Ar commented on index.html
> +            <li><a href="#"">サステナビリティマネジメント</a></li>
`"`が多いです

2020-07-26 14:03 UTC, n06Ar commented on index.html
> +            <li><a href="#"><img src="images/icon-facebook.svg" alt="Facebook"></a></li>
下部のFollowUsと画像サイズの指定が異なるので統一してください

2020-07-26 14:03 UTC, n06Ar commented on index.html
> +      <a xlink:href="/jp">
この`a`タグは`svg`タグを囲うようにしてください

2020-07-26 14:03 UTC, n06Ar commented on index.html
> +      <a xlink:href="/jp">
`xlink:href`を`href="#"`に直してください

2020-07-26 14:03 UTC, n06Ar commented on index.html
> +          <a class="linkLeft" href="#">&lt; ビジネスモデルの特徴</a>
`&lt;`は、CSSの擬似要素の`::before`を使って表示してください
それとこの箇所の文字の色は元のサイトの色に合わせてください
`.LinkRight`も同様です

2020-07-26 14:03 UTC, n06Ar commented on common/css/style.css
> +    color: #005bac;
記号の文字色を元のページに合わせて修正してください

2020-07-26 14:03 UTC, n06Ar commented on common/css/style.css
> +    color: #005bac;
記号の文字色を元のページに合わせて修正してください

2020-07-26 14:03 UTC, n06Ar commented on common/css/style.css
> +.footerMain .footerMainList p {
`.footerMain`で`p`タグが使われていないように見受けられます
もし使用していないのであれば削除してください

2020-07-26 14:04 UTC, n06Ar commented on index.html
> +<main>
こちらパンくずで解消されていたので対応は不要です

2020-07-26 14:05 UTC, n06Ar commented on index.html
> +<main>
こちら問題ないので修正不要です

2020-07-26 14:11 UTC, n06Ar requested changes

2020-07-26 14:11 UTC, n06Ar commented on index.html
> +<meta property="og:image" content="http://www.nri.com/-/media/Corporate/jp/Images/company/whats/story06/story06_s.jpg">
画像ですが、このリポジトリに保存してリポジトリ内の画像を参照するようにしてください

2020-07-27 07:27 UTC, kouyanh commented on common/css/style.css
> +#btn01.active span:nth-of-type(1) {
基本的にはコピーペーストする際に気をつけてもらいたいのですが、コードの意味が分かってコピーするのと、分かっていない状態で（とりあえず動くものは）コピーするものとでは意味合いが全然違ってきますので、特に後者の場合は力にならない事がありますので、お気をつけください。

2020-07-27 09:21 UTC, n06Ar commented on common/css/style.css
> +.footerMain .footerMainList p {
こちら私の見落としでした
申し訳ありませんが、読み捨てをお願いいたします

2020-07-27 09:22 UTC, n06Ar commented on common/css/style.css
> +    align-items: center;
修正確認しました

2020-07-27 09:55 UTC, n06Ar requested changes
レビューしました
追加で指摘があるためご確認をお願いいたします

また、追加していただいたPDFのアイコン画像が、元のサイトと異なるためご確認をお願いいたします

2020-07-27 09:55 UTC, n06Ar commented on common/css/style.css
> +.footerSub p {
ここは、`#copyright`でしか使われていないので、セレクタを`#copyright`に置き換えてください
どこで使われているかセレクタを見て判断できるようにするためです

2020-07-27 09:55 UTC, n06Ar commented on index.html
> +      <li><a href="#">免責条項</a></li>
ここの`li`タグ間に元のページと比較して、仕切り線がないので追加をお願いします

2020-07-27 09:55 UTC, n06Ar commented on index.html
> +<meta property="og:image" content="images/story06_s.jpg">
`og:image`は、フルパスを推奨なので`https://github.com/koya-sato-017/koyasato/blob/e2290cbe647ee498e3bae0b37741685ad8a7318e/images/story06_img_01.jpg?raw=true`を設定してください

2020-07-27 12:48 UTC, koya-sato-017 commented on common/css/style.css
> +.footerSub p {
#copyright に書き換えました。

2020-07-27 12:49 UTC, koya-sato-017 commented on index.html
> +      <li><a href="#">免責条項</a></li>
cssにて、
::beforeで実装しました。

2020-07-27 12:50 UTC, koya-sato-017 commented on index.html
> +<meta property="og:image" content="images/story06_s.jpg">
修正しました。

2020-07-27 12:59 UTC, koya-sato-017 commented on common/css/style.css
> +#btn01.active span:nth-of-type(1) {
そうですよね、、
コピペする際は、一度かみ砕いて理解するようにします。

2020-07-27 13:00 UTC, koya-sato-017 commented on common/css/style.css
> +    background: url(../../images/PDF_24.png) no-repeat;
pdf画像ファイル、変更しました。

2020-07-27 13:40 UTC, n06Ar commented
これが最後の指摘になると思います

- `Copyright`のフォントサイズを2px大きくしてください
- 下記画像のように画面を大きくするとズレるの左側を合わせるようにしてください
![フッターのずれ](https://user-images.githubusercontent.com/56122838/88548142-a52bcf80-d059-11ea-82b0-994a15a45165.png)

2020-07-27 14:47 UTC, n06Ar requested changes

2020-07-27 14:47 UTC, n06Ar commented on common/css/style.css
> +    width: 70%;
`width`ではなく`max-width`でかつ`px`指定をしてください
元のページの挙動ですと、`%`にすると画面サイズに合わせて横幅が動的に変化し左によってしまうので`px`指定をします
`width`だと画面が小さくなった際にその長さを維持してしまうため`max-width`を使用し回避します

`#copyright`も同様の修正をお願いします

2020-07-27 15:01 UTC, koya-sato-017 commented on common/css/style.css
> +    width: 70%;
そういうことなんですね。
max-widthに修正しました。

2020-07-27 15:05 UTC, n06Ar commented
LGTM!!

2020-08-01 08:36 UTC, n06Ar approved these changes

2020-08-17 05:05 UTC, merged