N高課題　HTMLコーディング
koya-sato-017/koyasato pull request #5
Opened 2020-08-01 12:59 UTC by koya-sato-017

2020-08-01 15:49 UTC, n06Ar requested changes
レビューしました
全体的にですが、alt属性の説明が不足しているので追記をお願いします
画像が表示されていなくてもどんな内容かわかるレベルが良いです

2020-08-01 15:49 UTC, n06Ar commented on html-nkou/index.html
> +                    <img src="images/footer05_nlabo.png" alt="N_Code_Labo">
alt属性に_をつけるとスクリーンリーダーなどがそのまま読み上げたりするので必要がない限り使用しないでください

2020-08-01 15:49 UTC, n06Ar commented on html-nkou/index.html
> +                <img src="images/footer02_tel01.png" alt="0120-0252-15">
alt属性が数字の羅列だとなんの数字か推測が難しいので電話番号などを情報として付与してください

2020-08-01 15:49 UTC, n06Ar commented on html-nkou/index.html
> +<nav class="localNav">
ナビゲーションなので最初の`header`タグの中に入れてください

2020-08-01 15:49 UTC, n06Ar commented on html-nkou/index.html
> +<meta property="og:image" content="images/logo_ogp.png">
OGP画像は相対パスで指定しないようにしてください
本来であればWebサーバーに画像を置き使用しますが、今回は代わりに下記のURLを使用してください
`https://github.com/koya-sato-017/koyasato/blob/b9710fbad4b5f297a599adce7f3bd66afc5754ff/html-nkou/images/logo_ogp.png?raw=true`

2020-08-01 15:49 UTC, n06Ar commented on html-nkou/index.html
> +                <img src="images/footer01_to_top01.png" alt="Page_Top">
alt属性は、ページ上部にもどるなどの方が良いです

2020-08-01 15:49 UTC, n06Ar commented on html-nkou/index.html
> +        <p>N高についてさらに詳細を知りたい方はこちら</p>
セクション内の文章からここは見出しで良いです

2020-08-02 01:11 UTC, koya-sato-017 commented on html-nkou/index.html
> +                    <img src="images/footer05_nlabo.png" alt="N_Code_Labo">
_ を削除しました。

2020-08-02 01:12 UTC, koya-sato-017 commented on html-nkou/index.html
> +                <img src="images/footer02_tel01.png" alt="0120-0252-15">
alt="電話番号0120-0252-15"
に修正しました。

2020-08-02 01:12 UTC, koya-sato-017 commented on html-nkou/index.html
> +<nav class="localNav">
headerタグの中に入れました。

2020-08-02 01:13 UTC, koya-sato-017 commented on html-nkou/index.html
> +<meta property="og:image" content="images/logo_ogp.png">
前回も指摘された内容でした、すみません。
上記URLに変更しました。

2020-08-02 01:14 UTC, koya-sato-017 commented on html-nkou/index.html
> +                <img src="images/footer01_to_top01.png" alt="Page_Top">
修正しました。

2020-08-02 01:14 UTC, koya-sato-017 commented on html-nkou/index.html
> +        <p>N高についてさらに詳細を知りたい方はこちら</p>
h2タグに変更しました。

2020-08-02 10:41 UTC, n06Ar requested changes
追加で指摘しました
個別で書きましたが、alt属性はスペースを禁止していませんので画像の説明になるのであれば問題ないです

2020-08-02 10:41 UTC, n06Ar commented on html-nkou/index.html
> +                    <img src="images/credo_card.jpg" alt="NSTANDARD">
alt属性は変数ではないので、`N STANDARD`のようにスペースをつけて良いです
スペースが禁止されると英語で説明文が書けないので使えます

2020-08-02 11:19 UTC, n06Ar requested changes

2020-08-02 11:19 UTC, n06Ar commented on html-nkou/index.html
> +                <img src="images/about_img02_02.png" alt="漁師体験、ファッション、酪農体験、ライター、ゲームプログラマ、パティシエ、ネイリスト、農業、受験勉強、数学、プログラミング、イラストレーター、漫画家、声優、小説家">
SEOの観点的にキーワードの列挙は避けてください
昔この手法で適切でないサイトのSEOの順位をあげようとした業者がいたことで問題になりました

2020-08-02 13:08 UTC, koya-sato-017 commented on html-nkou/index.html
> +                    <img src="images/credo_card.jpg" alt="NSTANDARD">
スペースをつけました。

2020-08-02 13:09 UTC, koya-sato-017 commented on html-nkou/index.html
> +                <img src="images/about_img02_02.png" alt="漁師体験、ファッション、酪農体験、ライター、ゲームプログラマ、パティシエ、ネイリスト、農業、受験勉強、数学、プログラミング、イラストレーター、漫画家、声優、小説家">
修正しました。

2020-08-03 11:17 UTC, n06Ar commented on html-nkou/index.html
> +                        <img src="images/about_img09_04.jpg" alt="提携スクールの画像">
コンテンツデザインが関わるのでimoとしてあげておきます
`Stanford、Oxford International Study Centerなどのスクールと提携しています`と書くと重要な情報を伝えることができSEO的にも効果があります

2020-08-03 11:19 UTC, n06Ar approved these changes
LGTMです
修正不要なimoのコメントをしました
参考程度に読んでみてください

2020-08-15 08:03 UTC, n06Ar commented on html-nkou/index.html
> +            <ul>
このリストの中がリンクになっていないです

2020-08-15 08:22 UTC, n06Ar requested changes
レビューしました
何点か指摘をしているのでご確認をお願いいたします

また、Safariでフォントが明朝体になっていたのでフォント設定を見直してください

2020-08-15 08:22 UTC, n06Ar commented on html-nkou/index.html
> +            <ul>
ここのリストの最後の生徒用ログイン以外が、リンクになっていないです

2020-08-15 08:22 UTC, n06Ar commented on html-nkou/index.html
> +                <li><a href="#">生徒用ログイン</a></li>
生徒用ログインのリンクの色が異なります

2020-08-15 08:22 UTC, n06Ar commented on html-nkou/common/css/style.css
> +    font-weight: 700;
700だとフォントが太いです

2020-08-15 08:22 UTC, n06Ar commented on html-nkou/common/css/style.css
> +    font-size: 4px;
Google ChromeとFirefoxで見る限り小さいです。
また位置も上よりです。

2020-08-15 08:22 UTC, n06Ar commented on html-nkou/common/css/style.css
> +    width: 100%;
パンくずが左よりで余白がないので、教育方針と同じ感じの余白をつけてください

2020-08-16 15:48 UTC, koya-sato-017 commented on html-nkou/index.html
> +            <ul>
aタグを追加しました。

2020-08-16 15:49 UTC, koya-sato-017 commented on html-nkou/index.html
> +                <li><a href="#">生徒用ログイン</a></li>
リンクの色修正しました。また、細かい部分を微調整しました。

2020-08-16 15:49 UTC, koya-sato-017 commented on html-nkou/common/css/style.css
> +    font-weight: 700;
フォントサイズ修正しました。

2020-08-17 03:34 UTC, koya-sato-017 commented on html-nkou/common/css/style.css
> +    width: 100%;
余白を調整しました。

2020-08-17 03:38 UTC, koya-sato-017 commented on html-nkou/common/css/style.css
> +    font-size: 4px;
フォントサイズ10pxにしました。

2020-08-17 15:33 UTC, n06Ar commented on html-nkou/common/css/style.css
> +    width: 100%;
すみませんが、下記の画像のような位置ぐらいまで少し調整をお願いします
![パンくずリストの余白の位置](https://user-images.githubusercontent.com/56122838/90413761-e1e36780-e0e9-11ea-88cc-4d2a86c6ff76.png)

2020-08-17 15:58 UTC, n06Ar requested changes
追加の指摘をしました
修正いただいたものにも指摘があるので気をつください
あと少しです！

2020-08-17 15:58 UTC, n06Ar commented on html-nkou/index.html
> +        <a class="mainLogo href="#">
classの`"`がないので気をつけてください

2020-08-17 15:58 UTC, n06Ar commented on html-nkou/common/css/style.css
> +    max-width: 1060px;
画面に固定されないヘッダーやコンテンツやフッターにも設定をしてください
1060px以下になると右側に余白ができてしまいます

2020-08-17 15:58 UTC, n06Ar commented on html-nkou/common/css/style.css
> +    background: url(../../images/icon_arrow01_right_black01.png) 0 6px no-repeat;
真ん中に来るように調整をお願いします
もし、下記の画像と表示が異なる場合は、教えてください
![Readmeの記号の位置が高い](https://user-images.githubusercontent.com/56122838/90414957-65518880-e0eb-11ea-86e3-8c60333b3a67.png)

2020-08-18 14:37 UTC, koya-sato-017 commented on html-nkou/common/css/style.css
> +    width: 100%;
失礼しました、再度余白を調整しました。
あまりclassを増やしたくなかったのですが、topicPathWrapperで囲みました。

リンクNo. 3f06939

2020-08-18 14:40 UTC, koya-sato-017 commented on html-nkou/index.html
> +        <a class="mainLogo href="#">
すみません、気がつかなかったです。修正しました。

2020-08-18 15:43 UTC, koya-sato-017 commented on html-nkou/common/css/style.css
> +    max-width: 1060px;
各箇所に top: 0,left: 0 を設定しました。

リンクNo. cf5256e

2020-08-18 15:57 UTC, koya-sato-017 commented on html-nkou/common/css/style.css
> +    background: url(../../images/icon_arrow01_right_black01.png) 0 6px no-repeat;
位置の調整をしました。

リンクNo. e0aea31

2020-08-18 16:45 UTC, n06Ar commented on html-nkou/common/css/style.css
> +    max-width: 1060px;
みたかぎりレイアウトに影響がなかったので修正は不要ですが、`top: 0;`と`left: 0;`ではなく`max-width: 1060px;`を他の箇所にもつけて欲しかった意図です

2020-08-18 16:51 UTC, n06Ar requested changes
一部指摘漏れがありましたので、追加の指摘をしました
申し訳ありませんが、ご確認をお願いします

2020-08-18 16:51 UTC, n06Ar commented on html-nkou/index.html
> +                <li><a href="#">ネットコース<br><img src="images/global_nav_btn01_02.png" alt="Net Course"></a></li>
Net Couseの画像が`hover`時に青文字になるようにしてください

2020-08-18 16:51 UTC, n06Ar commented on html-nkou/index.html
> +                <li>&gt; N高について</li>
`&gt;`は装飾なので、CSSで`:before`を使ってつけてみてください

2020-08-18 16:51 UTC, n06Ar commented on html-nkou/index.html
> +            <img class="underLine" src="images/line01_white01.png" alt="下線">
細かい指摘ですが、文書的に下線の意味は特にないのでalt属性を空にして`aria-hidden="true"`で記述して良いです

2020-08-19 04:16 UTC, koya-sato-017 commented on html-nkou/common/css/style.css
> +    max-width: 1060px;
そういう意図だったのですね、失礼しました。
とりあえず、修正せずそのままにしておきます。

2020-08-19 14:20 UTC, koya-sato-017 commented on html-nkou/index.html
> +                <li><a href="#">ネットコース<br><img src="images/global_nav_btn01_02.png" alt="Net Course"></a></li>
hover時に青文字になるようにしました。

リンクNo. 9767853

2020-08-19 14:43 UTC, koya-sato-017 commented on html-nkou/index.html
> +                <li>&gt; N高について</li>
cssで実装しました。

リンクNo. 0c02f50

2020-08-19 14:57 UTC, koya-sato-017 commented on html-nkou/index.html
> +            <img class="underLine" src="images/line01_white01.png" alt="下線">
修正しました。

リンクNo. 83cc3ab

2020-08-19 15:53 UTC, n06Ar commented on html-nkou/index.html
> +                <li><a href="#">ネットコース<br><img src="images/global_nav_btn01_02.png" alt="Net Course"></a></li>
画像に`hover`した時のみになっているので、aタグを`hover`した時に画像を青文字になるようにしてください

2020-08-20 12:04 UTC, koya-sato-017 commented on html-nkou/index.html
> +                <li><a href="#">ネットコース<br><img src="images/global_nav_btn01_02.png" alt="Net Course"></a></li>
hover時の挙動を再度修正しました。

リンクNo. 0064fd3

2020-08-20 15:49 UTC, n06Ar commented
LGTMです！

2020-08-20 15:53 UTC, n06Ar commented on html-nkou/common/css/style.css
> +    max-width: 1060;
pxを忘れています

2020-08-20 16:12 UTC, n06Ar reviewed
imo的なコメントです
修正は不要ですが、ちょっと気になったことやこうしても良い的なことを書いています
興味があったら読んでみてください

2020-08-20 16:12 UTC, n06Ar commented on html-nkou/common/css/style.css
> +    display: flex;
おそらくテーブルを使っているのでこちらは不要ですね

2020-08-20 16:12 UTC, n06Ar commented on html-nkou/common/css/style.css
> +    padding: 0px 10px;
0px の場合は0で良いです

2020-08-20 16:12 UTC, n06Ar commented on html-nkou/common/css/style.css
> +    letter-spacing: 0.9px;
細かいことですが、ピクセルを小数点指定をするとブラウザによって表示結果が変わるので避けた方がいいです

2020-08-20 16:12 UTC, n06Ar commented on html-nkou/common/css/style.css
> +    background-position: 50% -10px;
hover系のスタイルですが、`background-position`意外は不要です
`.headerMainBottom ul li:nth-child(2) a .image`ですでに他の要素は指定済みです。

この理由を説明すると長いので、興味ありましたら質問してください

2020-08-22 12:05 UTC, merged